repos:
    - repo: local
      hooks:
          - id: cargo-fmt
            name: Cargo Formatter
            description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
            entry: cargo fmt --all
            pass_filenames: false
            types: [file, rust]
            language: system
          - id: cargo-linter
            name: Cargo Linter
            description: Run cargo linter on files included in the commit. clippy should be installed before-hand.
            entry: cargo clippy --fix --allow-dirty
            pass_filenames: false
            types: [file, rust]
            language: system
