[package]
name = "gx"
description = "CLI to manage GitHub Actions dependencies"
edition = "2024"
license = "MIT"
version = "0.1.0"

[dependencies]
anyhow = "1"
gix = "0.78.0"
glob = "0.3"
clap = { version = "4", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3"
