[package]
name = "gx"
description = "CLI to manage GitHub Actions dependencies"
edition = "2024"
license = "MIT"
version = "0.1.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
gix-discover = "0.46.0"
glob = "0.3"
log = "0.4"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
