[workspace]
members = ["crates/gx-lib", "crates/gx"]
resolver = "2"

[workspace.lints.rust]
unused-crate-dependencies = "deny"
warnings = "warn"

[workspace.lints.clippy]
pedantic = "deny"

[profile.dist]
inherits = "release"
lto = "thin"
