[workspace]
members = ["crates/gx-lib", "crates/gx"]
resolver = "2"

[workspace.dependencies]
# local
gx-lib = { path = "crates/gx-lib", version = "0.0.0" }

# third-party
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
gix-discover = "0.46.0"
glob = "0.3"
log = "0.4"
regex = "1"
reqwest = { version = "0.13", features = ["blocking", "json"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde-saphyr = "0.0.21"
tempfile = "3"
thiserror = "2"
toml = "0.9"

[workspace.lints.rust]
unused-crate-dependencies = "deny"
warnings = "warn"

[workspace.lints.clippy]
pedantic = "deny"

[profile.dist]
inherits = "release"
lto = "thin"
