# Basic actions
[actions]
actions/checkout = "v4"

# Manual actions
[actions]
actions/checkout = [
{commit_hash = "123", ref = "main", path=".github/workflows/build.yml>checkout.0"}
]

# Actions Overrides
[actions]
"actions/checkout" = [
{ path = "**/*", ref = "v4" },
{ path = ".github/legacy-workflow.yml", ref = "v3" }
]

"aws-actions/configure-aws-credentials" = [
{ path = "**/*", ref = "v1" },
{ path = ".github/experimental.yml", ref = "v1" }
]
